<?php
/**
* OWASP Enterprise Security API (ESAPI)
* 
* @author Ishida, M‡rcio AndrŽ (mishida@conviso.com.br)
* Created on Feb 9, 2010
*/
	session_start();	
	$orig = session_id();
	session_regenerate_id();
	$newOrig = session_id();

	setcookie("cookie",$newOrig);
	$cookies = session_get_cookie_params();


	import_request_variables("gp", "rvar_");
	include("header.php");

?>


<h2 align="center">Exercise: Change Session Identifier</h2>

<p>Original Cookie (saved in session)</p>
<table align="center" border="1" width="60%"><tr><td align="center">
	<br>JSESSIONID=<?=$orig ?><br><br>
</td></tr></table>

<p>Current Cookie (generated by JavaScript in browser)</p>
<table align="center" border="1" width="60%"><tr><td align="center">
	<br><script>document.write(document.cookie)</script><br><br>
</td></tr></table>

<p>Click <a href="ChangeSessionIdentifierSecure.php?function=ChangeSessionIdentifier&mode=secure">here</a> to refresh the page with a new session identifier.</p>

<?php include("footer.php");  ?>